version: "3"
services:
  app:
    env_file: .env.sample
    build: .
    depends_on:
      - postgres
    ports:
      - "3050:3050"

  postgres:
    image: postgres:11.2-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: polyflow

networks:
  default:
    external:
      name: polyflow
