version: 2.1
orbs:
  aws-ecs: circleci/aws-ecs@0.0.19
  docker: circleci/docker@0.5.17
  codecov: codecov/codecov@1.0.5
jobs:
  test:
    docker:
      - image: circleci/node:12.11.0
    steps:
      - checkout
      - run: yarn
      - run: yarn test:cover
      - codecov/upload:
          file: './coverage/lcov.info'

  new-version:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: yarn
      - run: yarn new-version

workflows:
  test-tag:
    jobs:
      - test:
          filters:
            tags:
              ignore: /^v\d+\.\d+\.\d+$/
            branches:
              ignore: /dependeabot\/*/
      - new-version:
          context: github
          requires: [test]
          filters:
            branches:
              only: [master]
  build-deploy:
    jobs:
      - docker/publish:
          image: ${CIRCLE_PROJECT_REPONAME}
          context: docker
          tag: ${CIRCLE_TAG}
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+$/
      - aws-ecs/deploy-service-update:
          family: '${CIRCLE_PROJECT_REPONAME}'
          cluster-name: polyflow
          container-image-name-updates: 'container=${CIRCLE_PROJECT_REPONAME},tag=${CIRCLE_TAG}'
          context: aws
          requires: [docker/publish]
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+$/
