version: 2.1
orbs:
  docker: circleci/docker@0.5.17
  codecov: codecov/codecov@1.0.5
jobs:
  test:
    docker:
      - image: circleci/node:12.11.0
    steps:
      - checkout
      - run: yarn
      - run: yarn lint:ci
      - run: yarn test:cover
      - codecov/upload:
          file: './coverage/lcov.info'

workflows:
  test-tag:
    jobs:
      - test:
          filters:
            tags:
              ignore: /^v\d+\.\d+\.\d+$/
            branches:
              ignore: /dependeabot\/*/
  build-deploy:
    jobs:
      - docker/publish:
          image: yanmendes/${CIRCLE_PROJECT_REPONAME}
          context: docker
          tag: ${CIRCLE_TAG}
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+$/
